# Generated by Django 5.0.6 on 2024-07-06 12:52

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recensione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
                ('data_inserimento', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('utente_inserimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utente_ins', to=settings.AUTH_USER_MODEL)),
                ('utente_riferimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utente_rif', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
