# Generated by Django 5.0.6 on 2024-06-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annunci', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annuncio',
            name='potenza',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
