# Generated by Django 5.0.6 on 2024-06-25 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annunci', '0002_annuncio_potenza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annuncio',
            name='potenza',
        ),
    ]
