# Generated by Django 5.0.6 on 2024-07-05 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annunci', '0002_alter_annuncio_utente_recensione'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Annuncio',
        ),
    ]
