# Generated by Django 5.0.6 on 2024-07-05 07:14

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annunci', '0003_delete_annuncio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=20)),
                ('modello', models.CharField(max_length=30)),
                ('anno', models.IntegerField()),
                ('prezzo', models.IntegerField()),
                ('chilometraggio', models.IntegerField()),
                ('potenza', models.IntegerField()),
                ('cilindrata', models.IntegerField()),
                ('stato', models.CharField(max_length=20)),
                ('carburante', models.CharField(max_length=20)),
                ('cambio', models.CharField(max_length=20)),
                ('colore', models.CharField(max_length=30)),
                ('immagine', models.CharField(max_length=64)),
                ('descrizione', models.CharField(max_length=200)),
                ('data_inserimento', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
