# Generated by Django 5.0.6 on 2024-06-25 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annunci', '0003_remove_annuncio_potenza'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Annuncio',
        ),
    ]
