# Generated by Django 5.0.6 on 2024-06-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annunci', '0004_delete_annuncio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=20)),
                ('modello', models.CharField(max_length=30)),
                ('anno', models.IntegerField()),
                ('prezzo', models.IntegerField()),
                ('chilometraggio', models.IntegerField()),
                ('potenza', models.IntegerField()),
            ],
        ),
    ]
