# Generated by Django 5.0.6 on 2024-07-06 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annunci', '0004_annuncio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recensione',
        ),
    ]
