# Generated by Django 5.0.6 on 2024-07-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annunci', '0005_delete_recensione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annuncio',
            name='immagine',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
