# Generated by Django 5.0.6 on 2024-07-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annunci', '0008_alter_annuncio_immagine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annuncio',
            name='immagine',
            field=models.ImageField(upload_to='media/uploads/'),
        ),
    ]
