# Generated by Django 5.0.6 on 2024-07-07 13:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annunci', '0009_alter_annuncio_immagine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annuncio',
            name='data_inserimento',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
